site_name: Datafaker
site_url: https://www.datafaker.net
site_author: Erik Pragt
site_description: >-
  Create fake data for your JVM programs within minutes, 
  using our wide range of more than 250 data providers

repo_name: datafaker-net/datafaker
repo_url: https://github.com/datafaker-net/datafaker
edit_uri: "edit/main/docs"

# Copyright
copyright: Copyright &copy; 2016 - 2025 Erik Pragt

theme:
  name: material
  custom_dir: material
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: datafaker-net
      repo: datafaker
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - macros
  - minify:
      minify_html: true

# Customization
extra:
  datafaker:
    version: 2.5.2
    snapshot: 2.5.3-SNAPSHOT

# Page tree
nav:
  - Home: index.md
  - Documentation:
    - Getting started: documentation/getting-started.md
    - Basic usage: documentation/usage.md
    - Data Providers:
      - All providers: documentation/providers.md
      - Custom providers: documentation/custom-providers.md
    - Advanced usage:
      - Sequences: documentation/sequences.md
      - Date format: documentation/date-format.md
      - Advanced password generation: documentation/password.md
      - Expressions: documentation/expressions.md
      - Formats: documentation/formats.md
      - Transformation schemas: documentation/schemas.md
      - Unique values: documentation/unique-values.md
    - Performance:
      - Datafaker 1.4.0: documentation/performance140.md
      - Datafaker 1.7.0: documentation/performance170.md
    - Javadoc: 'https://s01.oss.sonatype.org/service/local/repositories/releases/archive/net/datafaker/datafaker/2.5.2/datafaker-2.5.2-javadoc.jar/!/index.html'
    - Contributing: documentation/contributing.md
    - First time contributor: documentation/first-time-contributor.md
    - License: documentation/license.md
#    - Changelog:
#      - Changes: changelog/index.md
#      - How to upgrade: upgrade.md
  - Releases:
    - 2.6.0-SNAPSHOT: releases/2.6.0-SNAPSHOT.md
    - 2.5.3: releases/2.5.3.md
    - 2.5.2: releases/2.5.2.md
    - 2.5.1: releases/2.5.1.md
    - 2.5.0: releases/2.5.0.md
    - 2.4.4: releases/2.4.4.md
    - 2.4.3: releases/2.4.3.md
    - 2.4.2: releases/2.4.2.md
    - 2.4.1: releases/2.4.1.md
    - 2.4.0: releases/2.4.0.md
    - 2.3.1: releases/2.3.1.md
    - 2.3.0: releases/2.3.0.md
    - 2.2.2: releases/2.2.2.md
    - 2.2.1: releases/2.2.1.md
    - 2.2.0: releases/2.2.0.md
    - 2.1.0: releases/2.1.0.md
    - 2.0.2: releases/2.0.2.md
    - 2.0.1: releases/2.0.1.md
    - 2.0.0: releases/2.0.0.md
    - 1.9.0: releases/1.9.0.md
    - 1.8.0: releases/1.8.0.md
    - 1.7.0: releases/1.7.0.md
    - 1.6.0: releases/1.6.0.md
    - 1.5.0: releases/1.5.0.md
    - 1.4.0: releases/1.4.0.md
    - 1.3.0: releases/1.3.0.md
    - 1.2.0: releases/1.2.0.md
    - 1.1.0: releases/1.1.0.md
    - 1.0.0: releases/1.0.0.md
    - 0.9.0: releases/0.9.0.md
  - In the news: in-the-media/links.md
