# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main, 1.x ]
  pull_request:
    paths-ignore:
      - 'material/**'
      - 'docs/**'
      - '**.md'
    branches: [ main, 1.x ]

env:
  # Quotes are here since Windows has issues with parsing of maven args with dots
  mvn_options: --batch-mode -q "-Dstyle.color=always" "-Dorg.slf4j.simpleLogger.showDateTime=true" "-Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss.SSS"
  jdk_for_downstream: 17
  os_for_downstream: ubuntu-latest

jobs:
  build:
    strategy:
      matrix:
        java-version: [ 17, 21, 25-ea ]
        runs-on: [ ubuntu-latest, ubuntu-24.04-arm, macos-latest, windows-latest ]
    name: Jdk ${{ matrix.java-version }}, os ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: ./mvnw $mvn_options install -PnoGpg --file pom.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5.5.1
        if: ${{ matrix.java-version == env.jdk_for_downstream && matrix.runs-on == env.os_for_downstream}}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - id: version-extract
        if: ${{ matrix.java-version == env.jdk_for_downstream && matrix.runs-on == env.os_for_downstream}}
        run: |
          echo "release_version=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
      - name: 'Download downstream project'
        if: ${{ matrix.java-version == env.jdk_for_downstream && matrix.runs-on == env.os_for_downstream}}
        uses: actions/checkout@v5
        with:
          repository: datafaker-net/datafaker-gen
          fetch-depth: 1
          path: datafaker_gen
      - name: 'Test with downstream project'
        if: ${{ matrix.java-version == env.jdk_for_downstream && matrix.runs-on == env.os_for_downstream}}
        run: cd datafaker_gen && ./mvnw clean install -Ddatafaker.version=${{ steps.version-extract.outputs.release_version }} -DskipBigQueryIntegrationTests=true
      - name: 'Upload test results'
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report-${{matrix.runs-on}}-${{matrix.java-version}}
          retention-days: 14
          path: |
            **/target/site
            **/target/surefire-reports
